// ── AUTOMATICALLY UPDATES TO CURRENT MONTH & YEAR ─────────────────────────
const now = new Date();
export const CALENDAR_MONTH = now.getMonth()   // 0-indexed: 0 = Jan, 4 = May, 5 = June, etc.
export const CALENDAR_YEAR  = now.getFullYear()
// ──────────────────────────────────────────────────────────────────────────
export interface Event {
  id:          number
  date:        number
  day:         string
  name:        string
  venue:       string
  time:        string
  categories:  string[]
  isFree:      boolean
  description: string
}

export const PREVIEW_EVENTS: Event[] = [
  {
    id: 1, date: 2, day: "Sat",
    name: "Vogue Café — Pre-Met Pop-Up",
    venue: "Spring St & Sixth Ave, SoHo",
    time: "May 2–4, 10AM–5PM",
    categories: ["fashion", "popup"],
    isFree: false,
    description: "Vogue's roaming café concept arrives in Manhattan for the first time, landing on the corner of Spring and Sixth in SoHo ahead of the first Monday in May. Presented with Chase Sapphire Reserve, the airy space features editorial displays, a live taping of The Run-Through with Vogue, a figure-drawing experience by Happy Medium, and a hand-painted monogram charm bar. It is the city's most stylish pre-Gala ritual — and it is open to the public.",
  },
  {
    id: 2, date: 3, day: "Sun",
    name: "The People's Ball — Eve of the Met",
    venue: "Brooklyn Central Library",
    time: "Evening",
    categories: ["gala", "free"],
    isFree: true,
    description: "On the eve of the Met Gala, Brooklyn Central Library hosts the People's Ball — a free, open counter-gala that invites all New Yorkers to walk its runway. The 2026 edition celebrates the 250th anniversary of American fashion, honoring Bethann Hardison and June Ambrose, with a performance by Melba Moore and hosting by Bevy Smith. It is the Met's democratized twin, and the most joyfully dressed crowd in all of Brooklyn.",
  },
  {
    id: 3, date: 4, day: "Mon",
    name: "The 2026 Met Gala — Fashion Is Art",
    venue: "The Metropolitan Museum of Art",
    time: "Invitation only",
    categories: ["gala", "fashion"],
    isFree: false,
    description: "Fashion's most anticipated evening of the year unfolds on the steps of the Metropolitan Museum of Art, where culture, entertainment, and design converge beneath the theme 'Fashion Is Art.' Invitation-only and relentlessly documented, the Met Gala marks the opening of the Costume Institute's annual exhibition and sets the cultural conversation for the season. For those in New York, the energy spills into the streets long before the doors open.",
  },
  {
    id: 4, date: 7, day: "Thu",
    name: "NYC Ballet Spring Gala — Set in Stone",
    venue: "David H. Koch Theater, Lincoln Center",
    time: "5:30PM",
    categories: ["gala", "art"],
    isFree: false,
    description: "New York City Ballet's Spring Gala opens at 5:30PM with a Ruinart Champagne reception before the world premiere of Set in Stone, a new work by NYCB principal dancer and choreographer Tiler Peck performed to Édouard Lalo's Symphonie Espagnole, with three-time Grammy winner Hilary Hahn on solo violin with the NYCB Orchestra. The program closes with Balanchine's Diamonds set to Tchaikovsky, followed by a black-tie dinner and dancing on the Promenade. It is one of Lincoln Center's most coveted gala evenings of the year.",
  },
  {
    id: 5, date: 8, day: "Fri",
    name: "Citi Concert Series — Zara Larsson",
    venue: "Rockefeller Plaza",
    time: "Free outdoor concert",
    categories: ["free"],
    isFree: true,
    description: "The Citi Concert Series opens its outdoor season at Rockefeller Plaza with Swedish pop star Zara Larsson, known for her powerful vocals and catalog spanning pop, R&B, and dance. The free concert is open to all with no tickets required, though early arrival is strongly recommended to secure a view of the main stage. It is midtown's best free evening of the early spring.",
  },
  {
    id: 6, date: 10, day: "Sun",
    name: "Costume Art Exhibition Opens",
    venue: "The Met, Condé M. Nast Galleries",
    time: "Opens May 10",
    categories: ["art", "fashion"],
    isFree: false,
    description: "The Metropolitan Museum of Art opens its annual Costume Institute exhibition in the Condé Nast Galleries, placing high fashion in direct dialogue with fine art traditions and the season's central theme. For those who missed the Gala, this is the most refined way to engage with the conversation at your own pace — no dress code, no invitation list. The exhibition runs through the summer.",
  },
  {
    id: 7, date: 14, day: "Thu",
    name: "Bryant Park Cuban Salsa Festival",
    venue: "Bryant Park",
    time: "6PM–10PM",
    categories: ["free"],
    isFree: true,
    description: "Bryant Park's lawns become an open-air dance floor for an evening of Cuban salsa, featuring live music from New York's Latin scene and instruction for dancers at every level. Running from 6 to 10PM, the free festival draws an exuberant cross-section of the city in one of Midtown's most beloved public spaces. Come in something you can move in.",
  },
  {
    id: 8, date: 16, day: "Sat",
    name: "Park Avenue Day 2026",
    venue: "Park Avenue, 34th–40th St",
    time: "10AM–6PM",
    categories: ["free", "art"],
    isFree: true,
    description: "Park Avenue Day closes six blocks of the city's most elegant boulevard to traffic, transforming them into a pedestrian promenade lined with art installations, live performances, and free programming from 10AM to 6PM. The annual celebration spotlights New York's cultural institutions and the communities that line the corridor — and the people-watching alone is worth the trip. One of the city's great free civic events.",
  },
]

export const FULL_EVENTS: Event[] = [
  ...PREVIEW_EVENTS,
  {
    id: 9, date: 1, day: "Fri",
    name: "Made in NYC Week Opens",
    venue: "Citywide — studios, markets, boutiques",
    time: "May 1–7",
    categories: ["popup", "free"],
    isFree: true,
    description: "Made in NYC Week opens across studios, markets, and boutiques citywide, celebrating the designers, craftspeople, and makers who produce goods entirely within the five boroughs. For seven days, participating businesses open for behind-the-scenes tours, sample sales, and limited-edition releases available only to those who show up in person. A rare opportunity to connect directly with the talent shaping New York's maker economy.",
  },
  {
    id: 10, date: 1, day: "Fri",
    name: "Audible Story House Opens",
    venue: "260 Bowery",
    time: "May 1–31, Wed–Sun",
    categories: ["art", "free"],
    isFree: true,
    description: "Audible opens its first-ever physical space at 260 Bowery — a free, 6,000-square-foot immersive listening lounge with seven distinct rooms, Dolby Atmos sound, and over 300 audio titles navigable via physical 'story tiles.' Open Wednesday through Sunday throughout May, the space hosts book clubs, live tapings, and curated programming in addition to its open listening experience. One of the most genuinely transportive free installations the city is offering this spring.",
  },
  {
    id: 11, date: 2, day: "Sat",
    name: "TikTok Shop Beauty Besties Pop-Up",
    venue: "25 Little W 12th St, Meatpacking",
    time: "10AM–4PM",
    categories: ["beauty", "popup"],
    isFree: true,
    description: "TikTok Shop brings its Beauty Besties pop-up to the Meatpacking District for a one-day event featuring live demonstrations, product sampling, and appearances by the platform's most-followed beauty creators. Styled as a social-first shopping experience, it offers photo moments and exclusive bundles available only to attendees. An opportunity to meet the faces behind the feeds in person.",
  },
  {
    id: 12, date: 2, day: "Sat",
    name: "Wella Professionals — The Wella Vault",
    venue: "NYC",
    time: "May 2",
    categories: ["beauty", "popup"],
    isFree: false,
    description: "Wella Professionals debuts The Wella Vault, an exclusive pop-up showcasing the brand's archival heritage and latest professional haircare innovations in a gallery-style format. Designed for industry insiders and color-focused beauty enthusiasts alike, the activation offers hands-on discovery of Wella's signature color systems alongside archival imagery from the brand's century-long history. Location details are released to confirmed attendees. [Note: Limited public information found — recommend verifying current event details with Wella directly.]",
  },
  {
    id: 13, date: 2, day: "Sat",
    name: "Blake Brown Beauty Pop-Up Truck",
    venue: "Union Square → SoHo Target",
    time: "12PM–5PM",
    categories: ["beauty", "popup"],
    isFree: true,
    description: "Blake Brown Beauty takes its pop-up truck from Union Square to SoHo Target, offering free product samples, styling consultations, and a first look at new launches from Blake Lively's salon-quality haircare brand. The mobile activation creates an approachable, unexpected moment in two of Manhattan's most trafficked neighborhoods — follow the brand's social channels for real-time location updates. Runs from noon to 5PM.",
  },
  {
    id: 15, date: 4, day: "Mon",
    name: "got2b Non-Stop Store",
    venue: "Union Square + roving NYC",
    time: "10AM–6PM",
    categories: ["beauty", "popup"],
    isFree: true,
    description: "Schwarzkopf's got2b opens a temporary Non-Stop Store at Union Square, merging retail with interactive styling stations, free product gifts, and live demonstrations from 10AM to 6PM. The activation targets a younger, style-forward consumer with content creation stations and roving components across other NYC neighborhoods throughout the day. Free to attend and open to the public.",
  },
  {
    id: 16, date: 7, day: "Thu",
    name: "Beauty of Joseon SPF Pop-Up",
    venue: "Times Square Plaza",
    time: "May 7–8",
    categories: ["beauty", "popup"],
    isFree: true,
    description: "K-beauty cult brand Beauty of Joseon takes over Times Square Plaza for two days with a free pop-up celebrating the launch of its expanded SPF line, offering skin consultations and complimentary products while supplies last. It is a rare physical touchpoint for a brand whose New York following has been built almost entirely online. Expect a crowd — Beauty of Joseon's Times Square appearances tend to sell out of samples within the first hour.",
  },
  {
    id: 17, date: 9, day: "Sat",
    name: "NYC Community Week Opens",
    venue: "100+ venues across all 5 boroughs",
    time: "May 9–17",
    categories: ["free"],
    isFree: true,
    description: "NYC Community Week launches across more than 100 venues spanning all five boroughs, spotlighting the nonprofits, mutual aid groups, and civic institutions doing essential work in New York's neighborhoods. Programming ranges from open houses and guided tours to workshops, block parties, and volunteer opportunities — all free, all designed for residents who want to engage more deeply with the city around them. A week-long reminder of everything New York does quietly, and beautifully, without cameras.",
  },
  {
    id: 18, date: 10, day: "Sun",
    name: "Macy's Flower Show — Final Day",
    venue: "Macy's Herald Square",
    time: "Last day",
    categories: ["beauty", "popup"],
    isFree: false,
    description: "Macy's annual Flower Show closes today — its final opportunity to walk the flagship Herald Square store's elaborate indoor botanical installations, transforming the retail floor into a landscape of rare blooms, sculptural arrangements, and fragrant seasonal displays. One of New York's most beloved spring traditions since 1946, the last day typically draws some of the season's most devoted visitors. Worth a visit before the city moves on to summer.",
  },
  {
    id: 19, date: 11, day: "Mon",
    name: "WWD Beauty CEO Summit Opens",
    venue: "The Breakers, Palm Beach, FL",
    time: "May 11–13",
    categories: ["industry"],
    isFree: false,
    description: "WWD's Beauty CEO Summit convenes the most influential executives in the global beauty industry for three days of keynote presentations, roundtables, and off-the-record conversations at The Breakers in Palm Beach. The invitation-only program brings together leaders from prestige, mass, and emerging beauty brands to discuss market dynamics, consumer behavior, and investment priorities for the year ahead. The ideas surfaced here tend to define the industry conversations that follow all season.",
  },
  {
    id: 20, date: 11, day: "Mon",
    name: "Spring Waterfront Benefit — The Frying Pan",
    venue: "The Frying Pan, Hudson River",
    time: "7PM–10PM",
    categories: ["gala"],
    isFree: false,
    description: "The Frying Pan — the beloved converted lightship moored at Pier 66 on the Hudson River — hosts its annual Spring Waterfront Benefit in support of Hudson River Community Sailing's youth and community programs. The evening runs from 7 to 10PM, offering cocktails against the backdrop of the West Side skyline and the kind of effortless waterfront energy that only New York's floating venues can produce. A well-dressed, good-spirited crowd makes this one of the season's most enjoyable causes.",
  },
  {
    id: 21, date: 12, day: "Tue",
    name: "MoMA PS1 Annual Benefit",
    venue: "MoMA PS1, Queens",
    time: "7PM cocktails",
    categories: ["gala", "art"],
    isFree: false,
    description: "MoMA PS1's annual benefit doubles this year as the institution's 50th anniversary gala, honoring founder Alanna Heiss and Glenn D. Lowry in a celebration of five decades of contemporary art in Queens. The evening begins with cocktails at 7PM in the museum's iconic courtyard, with an after-party in collaboration with the Women's History Museum running late into the night. A defining moment for New York's contemporary art community.",
  },
  {
    id: 22, date: 12, day: "Tue",
    name: "Black-Tie Society Benefit",
    venue: "583 Park Avenue",
    time: "5:30PM",
    categories: ["gala"],
    isFree: false,
    description: "A formal black-tie benefit held at the landmark 583 Park Avenue ballroom — one of Manhattan's most beautiful and historic event spaces — with the evening beginning at 5:30PM. The event draws a well-appointed crowd of philanthropists, society figures, and cultural supporters for a cause evening that exemplifies New York's tradition of elegant charitable giving. Invitation details circulate through membership and society networks. [Note: Specific cause and host organization could not be confirmed — recommend verifying directly.]",
  },
  {
    id: 23, date: 12, day: "Tue",
    name: "ALO Dance Cardio at Hudson Yards",
    venue: "Backyard at Hudson Yards",
    time: "Biweekly, Tuesdays",
    categories: ["free"],
    isFree: true,
    description: "ALO Yoga's free biweekly dance cardio class returns to the Backyard at Hudson Yards on Tuesday evenings, led by instructors from the brand's wellness platform. The outdoor class is open to all levels and draws a lively mix of regulars and newcomers drawn as much by the Hudson River backdrop as the workout itself. One of the better free wellness moments the city offers this spring — bring water and something to move in.",
  },
  {
    id: 24, date: 14, day: "Thu",
    name: "RetailMediaIQ Pop-Up — VIP Night",
    venue: "422 W Broadway, SoHo",
    time: "Invite-only",
    categories: ["beauty", "industry"],
    isFree: false,
    description: "RetailMediaIQ opens its first-ever physical pop-up at 422 West Broadway in SoHo with a curated VIP evening for beauty industry professionals, brand partners, and press on May 14. The invitation-only night previews the space's editorial content format, brand collaborations, and product discovery experience before it opens to consumers the following day. An early look at one of the spring's more interesting intersections of beauty media and retail.",
  },
  {
    id: 25, date: 15, day: "Fri",
    name: "RetailMediaIQ — Consumer Days",
    venue: "422 W Broadway, SoHo",
    time: "May 15–17, 11AM–5PM",
    categories: ["beauty", "popup"],
    isFree: true,
    description: "RetailMediaIQ's SoHo pop-up opens to consumers from May 15 to 17 at 422 West Broadway, offering an editorial shopping experience with curated beauty discovery, brand activations, and live content programming from 11AM to 5PM each day. The concept merges the browsing experience of a specialty retailer with the content depth of a beauty media platform, drawing shoppers who want context alongside their purchases. Free and open to the public.",
  },
  {
    id: 27, date: 19, day: "Tue",
    name: "City Harvest Gala — Shaken, Not Stirred",
    venue: "NYC",
    time: "Evening",
    categories: ["gala"],
    isFree: false,
    description: "City Harvest's annual gala — one of New York's most well-attended philanthropic evenings of the spring season — takes on the playful theme 'Shaken, Not Stirred' for 2026, bringing together the city's charitable community for cocktails, dining, and fundraising in support of City Harvest's food rescue programs. The organization redirects surplus food from restaurants, farms, and manufacturers to New Yorkers facing food insecurity, distributing over 61 million pounds annually across all five boroughs. The gala is City Harvest's signature fundraising moment of the year.",
  },
  {
    id: 28, date: 22, day: "Fri",
    name: "Citi Concert Series — Bleachers",
    venue: "Rockefeller Plaza",
    time: "Free outdoor concert",
    categories: ["free"],
    isFree: true,
    description: "The Citi Concert Series continues at Rockefeller Plaza with Bleachers, the indie-pop project of producer and songwriter Jack Antonoff, whose dense anthemic sound has made him one of the most influential voices in contemporary pop. The free outdoor concert is open to all with no tickets required — early arrival is strongly recommended, as Bleachers' live shows draw sizeable and energized crowds. One of the season's most anticipated free evenings in Midtown.",
  },
  {
    id: 29, date: 28, day: "Thu",
    name: "Bryant Park Picnic Performances Opens",
    venue: "Bryant Park Lawn",
    time: "7PM",
    categories: ["free", "art"],
    isFree: true,
    description: "Bryant Park Picnic Performances launches its 2026 summer season on May 28 with the first in its series of more than two dozen free outdoor concerts, dance performances, and cultural events on the lawn behind the New York Public Library. This year's lineup includes New York City Opera, Carnegie Hall Citywide, Brass and Choir Festivals, and artists from around the world — all free, all open to the public, no registration required. Bring a blanket, claim a spot on the lawn, and stay for the evening.",
  },
  {
    id: 30, date: 29, day: "Fri",
    name: "Citi Concert Series — Charlie Puth",
    venue: "Rockefeller Plaza",
    time: "Free outdoor concert",
    categories: ["free"],
    isFree: true,
    description: "Platinum-selling singer-songwriter Charlie Puth performs live at Rockefeller Plaza as part of the Citi Concert Series, bringing his mix of polished pop and R&B to one of New York's most iconic outdoor stages. Known for his ear for melody and chart-topping collaborations, Puth is one of the season's most accessible and well-attended free concerts. No tickets required — doors open to the public, arrive early for a view of the main stage.",
  },
  {
    id: 31, date: 30, day: "Sat",
    name: "Carnegie Hall at Hudson Yards — Film Night",
    venue: "Backyard at Hudson Yards",
    time: "Free screening",
    categories: ["art", "free"],
    isFree: true,
    description: "Carnegie Hall's Citywide program partners with the Backyard at Hudson Yards for a free outdoor film screening of Beauty and the Beast, preceded by a live interactive concert from Carnegie Hall's acclaimed Ensemble Connect, whose performance draws on musical ideas from the film. The event begins at 11AM and is open to all — one of the more quietly beautiful free mornings New York offers this month, with the Hudson River as backdrop.",
  },
]

export const FILTERS = [
  { key: "all",      label: "All"      },
  { key: "gala",     label: "Galas"    },
  { key: "beauty",   label: "Beauty"   },
  { key: "free",     label: "Free"     },
  { key: "popup",    label: "Pop-ups"  },
  { key: "industry", label: "Industry" },
  { key: "art",      label: "Art"      },
]

export const PAYWALL_PREVIEW = [
  { date: 19, day: "Tue", name: "City Harvest Gala — Shaken, Not Stirred", venue: "NYC · Evening",                            tag: "Gala", isFree: false },
  { date: 22, day: "Fri", name: "Citi Concert Series — Bleachers",          venue: "Rockefeller Plaza · Free outdoor concert", tag: "Free", isFree: true  },
]
